---
- name: SHELL ; grab metashape-pro_2_0_0_amd64.tar.gz, unzip, mv to bin
  become: true
  unarchive:
    src: "{{ METASHAPE_PRO_URL }}"
    dest: /opt
    remote_src: yes

- name: GET_URL ; grab metashape_icon.jpg
  become: true
  get_url:
    url: "{{ METASHAPE_PRO_ICON_URL }}"
    dest: /opt/metashape-pro/metashape_icon.jpg

- name: COPY ; copy metashape.desktop
  become: true
  copy:
    src: metashape.desktop
    dest: /usr/share/applications/metashape.desktop

- name: FILE ; ensure correct perms for metashape-pro directory
  become: true
  file:
    path: /opt/metashape-pro
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

- name: APT ; install libxcb-xinerama0
  become: true
  apt:
    name: libxcb-xinerama0
    state: present

- name: LINEINFILE ; ensure AGISOFT_FLS (floating license server) env var in .profile
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: 'export AGISOFT_FLS={{ METASHAPE_LICENSE_SERVER_IP }}:5842'

- name: SHELL ; run conda activate and pip for meta20
  shell:
    cmd: "~/anaconda3/bin/conda run -n meta20 pip install {{ METASHAPE_PRO_WHL_MODULE }}"
  args:
    executable: /bin/bash
    